---
settings:
  name: Virtual Desktop Managed Service
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: zh-cn,us-en,ja-jp
sidebar:
  entries:
  - title: VDMS 文档
    url: "/index.html"
  - title: 入门
    entries:
    - title: 前提条件
      url: "/serviceoffering.prerequisites.html"
    - title: 服务摘要
      url: "/serviceoffering.servicesummary.html"
  - title: 教程
    entries:
    - title: 安装应用程序
      url: "/applications.installapplications.html"
    - title: 更新 Deploy VM 映像
      url: "/images.updateimages.html"
    - title: 将用户分配给应用程序组
      url: "/users.assigntoappgroup.html"
    - title: 获取域管理员凭据
      url: "/administration.pam.html"
    - title: 添加用户访问权限
      url: "/users.add.html"
    - title: 删除用户访问权限
      url: "/users.remove.html"
    - title: 添加 / 删除管理员
      url: "/administration.addremoveadmins.html"
  - title: VDM 常见问题解答
    entries:
    - title: VDS 管理员权限
      url: "/FAQ.vdsadminpermissions.html"
